### PR TITLE
makes filtre helmets hide hair and stuff / adds another custom filtre armor set

### PR DESCRIPTION
**Pull request by dawsonkeyes**
read title

this pr also slightly reorganizes the filtre armor .dm file to place all custom items at the bottom

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
i wish i knew how to use github

**Comment by Ephemeralis** [comment]
not a massive fan of ckey limiting this, would it be a dealbreaker if we made it available to everyone?

**Comment by Ephemeralis** [comment]
i am told vol already has a ckey bound one so i guess this is a moot point by now

**Comment by Paxilmaniac** [comment]
post screenshots of your armor i aint forking your repo just to look at it

**Comment by dawsonkeyes** [comment]
> post screenshots of your armor i aint forking your repo just to look at it

image
womp womp

**Comment by kittysmooch** [comment]
> /datum/area_spawn/lustwish_public could not find any suitable turfs on map Sector Nine Facility!

its so over

**Pull request merged**
